import type { Metadata } from "next";
import "./globals.css"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Ajout du lien vers la police Geist */}
        <link rel="stylesheet" href="https://geist-fonts.vercel.app/style.css" />
      </head>
      <body className="geist antialiased">{children}</body>
    </html>
  );
}
